// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemsApi.Data;

#nullable disable

namespace SemsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008065026_SeedLegacyStudents")]
    partial class SeedLegacyStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SemsApi.Models.AuthorizedEmailDomain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomainId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DomainId");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("AuthorizedEmailDomains");

                    b.HasData(
                        new
                        {
                            DomainId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Domain = "dmc.edu.ph",
                            InstitutionName = "DMC College Foundation, Inc.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SemsApi.Models.Eval.GuidanceEvaluationLog", b =>
                {
                    b.Property<int>("Recno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recno"));

                    b.Property<DateTime?>("DateEvaluated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Sy")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int?>("Term")
                        .HasColumnType("int");

                    b.HasKey("Recno");

                    b.ToTable("GuidanceEvaluationLog", "Eval");
                });

            modelBuilder.Entity("SemsApi.Models.Eval.GuidanceEvaluationResult", b =>
                {
                    b.Property<int>("Recno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recno"));

                    b.Property<int?>("CatNo")
                        .HasColumnType("int");

                    b.Property<int?>("QnNo")
                        .HasColumnType("int");

                    b.Property<int?>("RateVal")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sy")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int?>("Term")
                        .HasColumnType("int");

                    b.HasKey("Recno");

                    b.ToTable("GuidanceEvaluationResult", "Eval");
                });

            modelBuilder.Entity("SemsApi.Models.Eval.TeacherEvaluationCategory", b =>
                {
                    b.Property<int>("Recno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recno"));

                    b.Property<string>("CatName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CatNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("CatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatRn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EvalType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Recno");

                    b.ToTable("TeacherEvaluationCategory", "Eval");

                    b.HasData(
                        new
                        {
                            Recno = 1,
                            CatName = "Teaching Effectiveness",
                            CatNo = 1,
                            CatRate = 25.00m,
                            CatRn = "A",
                            EvalType = "Teacher Evaluation"
                        },
                        new
                        {
                            Recno = 2,
                            CatName = "Classroom Management",
                            CatNo = 2,
                            CatRate = 20.00m,
                            CatRn = "B",
                            EvalType = "Teacher Evaluation"
                        },
                        new
                        {
                            Recno = 3,
                            CatName = "Communication Skills",
                            CatNo = 3,
                            CatRate = 20.00m,
                            CatRn = "C",
                            EvalType = "Teacher Evaluation"
                        },
                        new
                        {
                            Recno = 4,
                            CatName = "Subject Knowledge",
                            CatNo = 4,
                            CatRate = 20.00m,
                            CatRn = "D",
                            EvalType = "Teacher Evaluation"
                        },
                        new
                        {
                            Recno = 5,
                            CatName = "Student Engagement",
                            CatNo = 5,
                            CatRate = 15.00m,
                            CatRn = "E",
                            EvalType = "Teacher Evaluation"
                        });
                });

            modelBuilder.Entity("SemsApi.Models.Eval.TeacherEvaluationResult", b =>
                {
                    b.Property<int>("Recno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recno"));

                    b.Property<int?>("CatNo")
                        .HasColumnType("int");

                    b.Property<string>("EvalType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QnNo")
                        .HasColumnType("int");

                    b.HasKey("Recno");

                    b.ToTable("TeacherEvaluationResult", "Eval");

                    b.HasData(
                        new
                        {
                            Recno = 1,
                            CatNo = 1,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher explains lessons clearly and in an organized manner.",
                            QnNo = 1
                        },
                        new
                        {
                            Recno = 2,
                            CatNo = 1,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher uses appropriate examples and illustrations.",
                            QnNo = 2
                        },
                        new
                        {
                            Recno = 3,
                            CatNo = 1,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher adjusts teaching methods to different learning styles.",
                            QnNo = 3
                        },
                        new
                        {
                            Recno = 4,
                            CatNo = 1,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher provides timely and constructive feedback on student work.",
                            QnNo = 4
                        },
                        new
                        {
                            Recno = 5,
                            CatNo = 2,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher maintains an orderly and respectful classroom environment.",
                            QnNo = 1
                        },
                        new
                        {
                            Recno = 6,
                            CatNo = 2,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher manages time effectively during class periods.",
                            QnNo = 2
                        },
                        new
                        {
                            Recno = 7,
                            CatNo = 2,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher handles student misbehavior fairly and consistently.",
                            QnNo = 3
                        },
                        new
                        {
                            Recno = 8,
                            CatNo = 2,
                            EvalType = "Teacher Evaluation",
                            QnName = "Classroom rules and expectations are clearly communicated.",
                            QnNo = 4
                        },
                        new
                        {
                            Recno = 9,
                            CatNo = 3,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher communicates expectations and instructions clearly.",
                            QnNo = 1
                        },
                        new
                        {
                            Recno = 10,
                            CatNo = 3,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher listens to and responds to student questions.",
                            QnNo = 2
                        },
                        new
                        {
                            Recno = 11,
                            CatNo = 3,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher uses language appropriate to the students' level.",
                            QnNo = 3
                        },
                        new
                        {
                            Recno = 12,
                            CatNo = 3,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher provides opportunities for students to express ideas.",
                            QnNo = 4
                        },
                        new
                        {
                            Recno = 13,
                            CatNo = 4,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher demonstrates thorough knowledge of the subject matter.",
                            QnNo = 1
                        },
                        new
                        {
                            Recno = 14,
                            CatNo = 4,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher relates the subject to real-life situations.",
                            QnNo = 2
                        },
                        new
                        {
                            Recno = 15,
                            CatNo = 4,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher stays updated with current developments in the field.",
                            QnNo = 3
                        },
                        new
                        {
                            Recno = 16,
                            CatNo = 4,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher answers content-related questions accurately.",
                            QnNo = 4
                        },
                        new
                        {
                            Recno = 17,
                            CatNo = 5,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher encourages active participation from all students.",
                            QnNo = 1
                        },
                        new
                        {
                            Recno = 18,
                            CatNo = 5,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher creates a motivating and supportive learning atmosphere.",
                            QnNo = 2
                        },
                        new
                        {
                            Recno = 19,
                            CatNo = 5,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher uses varied activities to sustain student interest.",
                            QnNo = 3
                        },
                        new
                        {
                            Recno = 20,
                            CatNo = 5,
                            EvalType = "Teacher Evaluation",
                            QnName = "The teacher recognizes and praises student effort and achievement.",
                            QnNo = 4
                        });
                });

            modelBuilder.Entity("SemsApi.Models.Eval.TeacherEvaluationStrength", b =>
                {
                    b.Property<int>("Recno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recno"));

                    b.Property<string>("CommentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvalType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Term")
                        .HasColumnType("int");

                    b.HasKey("Recno");

                    b.ToTable("TeacherEvaluationStrength", "Eval");
                });

            modelBuilder.Entity("SemsApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System Administrator",
                            IsActive = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classroom Teacher",
                            IsActive = true,
                            Name = "Teacher",
                            NormalizedName = "TEACHER",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Student",
                            IsActive = true,
                            Name = "Student",
                            NormalizedName = "STUDENT",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SemsApi.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            GradeLevel = "Grade 6",
                            SchoolYear = "2025-2026",
                            Section = "GRACE",
                            Status = "Active",
                            StudentNumber = "2020-0331",
                            UserId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            GradeLevel = "Grade 7",
                            SchoolYear = "2025-2026",
                            Section = "St. Solomon Leclerq",
                            Status = "Active",
                            StudentNumber = "2025-2219",
                            UserId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            GradeLevel = "Kindergarten",
                            SchoolYear = "2025-2026",
                            Section = "KINDERGARTEN",
                            Status = "Active",
                            StudentNumber = "2025-2235",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SemsApi.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SemsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92ac3653-5441-40f5-bb9a-cc1ed15f9fb9",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jelah.cuevas@dmc.edu.ph",
                            EmailConfirmed = true,
                            FirstName = "Jelah",
                            GoogleSubjectId = "test-google-sub-001",
                            LastName = "Cuevas",
                            LockoutEnabled = false,
                            NormalizedEmail = "JELAH.CUEVAS@DMC.EDU.PH",
                            NormalizedUserName = "JELAH.CUEVAS@DMC.EDU.PH",
                            PhoneNumberConfirmed = false,
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "jelah.cuevas@dmc.edu.ph"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "861e13a6-b684-49c8-a2ab-25c476f3f0cd",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shevonn.salasala@dmc.edu.ph",
                            EmailConfirmed = true,
                            FirstName = "Shevonn",
                            GoogleSubjectId = "test-google-sub-002",
                            LastName = "Salasala",
                            LockoutEnabled = false,
                            NormalizedEmail = "SHEVONN.SALASALA@DMC.EDU.PH",
                            NormalizedUserName = "SHEVONN.SALASALA@DMC.EDU.PH",
                            PhoneNumberConfirmed = false,
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "shevonn.salasala@dmc.edu.ph"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b5e1ea9-de26-428f-8af8-b1f8020d813c",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chaser.gone@dmc.edu.ph",
                            EmailConfirmed = true,
                            FirstName = "Chaser",
                            GoogleSubjectId = "test-google-sub-003",
                            LastName = "Gone",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHASER.GONE@DMC.EDU.PH",
                            NormalizedUserName = "CHASER.GONE@DMC.EDU.PH",
                            PhoneNumberConfirmed = false,
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "chaser.gone@dmc.edu.ph"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SemsApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SemsApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SemsApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SemsApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SemsApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SemsApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SemsApi.Models.Student", b =>
                {
                    b.HasOne("SemsApi.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SemsApi.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SemsApi.Models.Teacher", b =>
                {
                    b.HasOne("SemsApi.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SemsApi.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SemsApi.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
