using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SemsApi.Data;
using SemsApi.DTO;
using SemsApi.Models.Eval;
using SemsApi.Utilities;

namespace SemsApi.Controllers
{
    /// <summary>
    /// Dedicated controller for TeacherEvaluationCategory CRUD operations.
    /// All category management lives here; the original EvaluationController is left unchanged.
    /// </summary>
    [ApiController]
    [Route("api/evaluation/categories")]
    public class CategoryController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // ---------------------------------------------------------------------
        // READ
        // ---------------------------------------------------------------------

        /// <summary>
        /// List all categories. Optionally filter by evalType.
        /// Ordered by CatNo. Includes Recno for subsequent update/delete.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<List<CategoryResponseDto>>> GetAll(
            [FromQuery] string? evalType = null)
        {
            var query = _context.TeacherEvaluationCategories.AsQueryable();

            if (!string.IsNullOrWhiteSpace(evalType))
                query = query.Where(c => c.EvalType == evalType);

            var data = await query
                .OrderBy(c => c.CatNo)
                .Select(c => new CategoryResponseDto
                {
                    Recno = c.Recno,
                    EvalType = c.EvalType,
                    CatNo = c.CatNo,
                    CatRn = c.CatRn,
                    CatName = c.CatName,
                    CatRate = c.CatRate
                })
                .ToListAsync();

            return Ok(data);
        }

        /// <summary>
        /// Get a single category by Recno.
        /// </summary>
        [HttpGet("{recno:int}")]
        public async Task<ActionResult<CategoryResponseDto>> GetById(int recno)
        {
            var category = await _context.TeacherEvaluationCategories
                .FirstOrDefaultAsync(c => c.Recno == recno);

            if (category is null)
                return NotFound(new { message = "Category not found." });

            return Ok(CategoryHelper.MapToResponse(category));
        }

        // ---------------------------------------------------------------------
        // CREATE
        // ---------------------------------------------------------------------

        /// <summary>
        /// Create a new evaluation category.
        /// Requires Admin role. Recno is generated by the database.
        /// </summary>
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Create([FromBody] CategoryRequestDto request)
        {
            var validationError = CategoryHelper.Validate(request);
            if (validationError is not null)
                return BadRequest(new { message = validationError });

            var evalType = request.EvalType!.Trim();

            // Unique CatNo within the same EvalType
            var duplicateExists = await _context.TeacherEvaluationCategories
                .AnyAsync(c => c.EvalType == evalType && c.CatNo == request.CatNo);

            if (duplicateExists)
            {
                return Conflict(new
                {
                    message = "A category with the same category number already exists for this evaluation type."
                });
            }

            var entity = new TeacherEvaluationCategory
            {
                EvalType = evalType,
                CatNo = request.CatNo,
                CatRn = request.CatRn!.Trim(),
                CatName = request.CatName!.Trim(),
                CatRate = Math.Round(request.CatRate!.Value, 2)
            };

            _context.TeacherEvaluationCategories.Add(entity);
            await _context.SaveChangesAsync();

            var response = CategoryHelper.MapToResponse(entity);

            return CreatedAtAction(
                nameof(GetById),
                new { recno = entity.Recno },
                new { message = "Category created successfully.", data = response });
        }

        // ---------------------------------------------------------------------
        // UPDATE
        // ---------------------------------------------------------------------

        /// <summary>
        /// Update an existing evaluation category.
        /// Requires Admin role. Recno itself is never modified.
        /// </summary>
        //[Authorize(Roles = "Admin")]
        [HttpPut("{recno:int}")]
        public async Task<ActionResult> Update(int recno, [FromBody] CategoryRequestDto request)
        {
            var category = await _context.TeacherEvaluationCategories
                .FirstOrDefaultAsync(c => c.Recno == recno);

            if (category is null)
                return NotFound(new { message = "Category not found." });

            var validationError = CategoryHelper.Validate(request);
            if (validationError is not null)
                return BadRequest(new { message = validationError });

            var evalType = request.EvalType!.Trim();

            // Unique CatNo within the same EvalType (exclude current record)
            var duplicateExists = await _context.TeacherEvaluationCategories
                .AnyAsync(c => c.Recno != recno
                            && c.EvalType == evalType
                            && c.CatNo == request.CatNo);

            if (duplicateExists)
            {
                return Conflict(new
                {
                    message = "A category with the same category number already exists for this evaluation type."
                });
            }

            category.EvalType = evalType;
            category.CatNo = request.CatNo;
            category.CatRn = request.CatRn!.Trim();
            category.CatName = request.CatName!.Trim();
            category.CatRate = Math.Round(request.CatRate!.Value, 2);

            await _context.SaveChangesAsync();

            return Ok(new
            {
                message = "Category updated successfully.",
                data = CategoryHelper.MapToResponse(category)
            });
        }

        // ---------------------------------------------------------------------
        // DELETE
        // ---------------------------------------------------------------------

        /// <summary>
        /// Delete an evaluation category.
        /// Requires Admin role.
        /// Refuses deletion when TeacherEvaluationResult rows still reference the same EvalType + CatNo.
        /// </summary>
        //Authorize(Roles = "Admin")]
        [HttpDelete("{recno:int}")]
        public async Task<ActionResult> Delete(int recno)
        {
            var category = await _context.TeacherEvaluationCategories
                .FirstOrDefaultAsync(c => c.Recno == recno);

            if (category is null)
                return NotFound(new { message = "Category not found." });

            var hasDependentQuestions = await _context.TeacherEvaluationResults
                .AnyAsync(q => q.EvalType == category.EvalType
                            && q.CatNo == category.CatNo);

            if (hasDependentQuestions)
            {
                return Conflict(new
                {
                    message = "Cannot delete this category because evaluation questions are associated with it."
                });
            }

            _context.TeacherEvaluationCategories.Remove(category);
            await _context.SaveChangesAsync();

            return NoContent();
        }
    }
}